import { Theme } from '../types/theme';

export const themes: Record<string, Theme> = {
  theme1: {
    name: 'Minimalist',
    colors: {
      primary: '#2563eb',
      secondary: '#64748b',
      accent: '#0ea5e9',
      background: '#ffffff',
      surface: '#f8fafc',
      text: '#1e293b',
      textSecondary: '#64748b',
      border: '#e2e8f0',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
    },
    fonts: {
      primary: 'Inter, system-ui, sans-serif',
      secondary: 'Inter, system-ui, sans-serif',
      headingWeight: 'font-semibold',
      bodyWeight: 'font-normal',
    },
    layout: {
      type: 'default',
      headerHeight: 'h-16',
      containerPadding: 'px-4 md:px-6 lg:px-8',
      borderRadius: 'rounded-lg',
      shadow: 'shadow-sm',
    },
    spacing: {
      xs: 'p-2',
      sm: 'p-4',
      md: 'p-6',
      lg: 'p-8',
      xl: 'p-12',
    },
  },
  theme2: {
    name: 'Dark Professional',
    colors: {
      primary: '#8b5cf6',
      secondary: '#a78bfa',
      accent: '#06b6d4',
      background: '#0f172a',
      surface: '#1e293b',
      text: '#f1f5f9',
      textSecondary: '#94a3b8',
      border: '#334155',
      success: '#22c55e',
      warning: '#eab308',
      error: '#f87171',
    },
    fonts: {
      primary: 'Playfair Display, serif',
      secondary: 'Source Sans Pro, sans-serif',
      headingWeight: 'font-bold',
      bodyWeight: 'font-light',
    },
    layout: {
      type: 'sidebar',
      headerHeight: 'h-20',
      containerPadding: 'px-6 md:px-8 lg:px-12',
      borderRadius: 'rounded-xl',
      shadow: 'shadow-2xl',
    },
    spacing: {
      xs: 'p-3',
      sm: 'p-5',
      md: 'p-7',
      lg: 'p-10',
      xl: 'p-16',
    },
  },
  theme3: {
    name: 'Colorful Creative',
    colors: {
      primary: '#ec4899',
      secondary: '#f97316',
      accent: '#10b981',
      background: '#fef3c7',
      surface: '#ffffff',
      text: '#1f2937',
      textSecondary: '#6b7280',
      border: '#f3f4f6',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
    },
    fonts: {
      primary: 'Pacifico, cursive',
      secondary: 'Poppins, sans-serif',
      headingWeight: 'font-normal',
      bodyWeight: 'font-medium',
    },
    layout: {
      type: 'grid',
      headerHeight: 'h-24',
      containerPadding: 'px-4 md:px-8 lg:px-16',
      borderRadius: 'rounded-2xl',
      shadow: 'shadow-xl',
    },
    spacing: {
      xs: 'p-4',
      sm: 'p-6',
      md: 'p-8',
      lg: 'p-12',
      xl: 'p-20',
    },
  },
};